on:
  workflow_call:
    inputs:
      version-position:
        type: string
        required: true
        description: |
          Version position to bump on successful deployment.

          One of:
          - major
          - minor
          - patch

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up Dhall
        uses: dhall-lang/setup-dhall@v4
        with:
          version: 1.41.1

      - name: Build
        run: build-scripts/build.bash

      - name: Upload to object storage
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args:
            --acl public-read
            --follow-symlinks
            --delete
            --exclude '.*/*'
            --exclude 'build-scripts/*'
            --exclude 'src/*'
        env:
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
          AWS_REGION: ru-central1
          AWS_ACCESS_KEY_ID: ${{ secrets.SA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY_SECRET }}
          AWS_S3_BUCKET: pgenie.io
          SOURCE_DIR: dist

      - name: Bump version and push tag
        id: tag-release
        uses: mathieudutour/github-tag-action@v6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          default_bump: ${{ inputs.version_position }}
