on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete --exclude '.git/*'
        env:
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
          AWS_REGION: ru-central1
          AWS_ACCESS_KEY_ID: ${{ secrets.SA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY_SECRET }}
          AWS_S3_BUCKET: pgenie.io
