on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Upload to S3
    runs-on: ubuntu-latest
    steps:
      - name: Set up dhall
        uses: dhall-lang/setup-dhall@v4

      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Build
        run: |
          build-scripts/build.bash
          mv dist/index.html .
          rm -rf dist

      - name: Upload to S3
        uses: jakejarvis/s3-sync-action@master
        with:
          args:
            --acl public-read
            --follow-symlinks
            --delete
            --exclude '.*/*'
            --exclude 'build-scripts'
            --exclude 'src'
        env:
          AWS_S3_ENDPOINT: https://storage.yandexcloud.net
          AWS_REGION: ru-central1
          AWS_ACCESS_KEY_ID: ${{ secrets.SA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY_SECRET }}
          AWS_S3_BUCKET: pgenie.io
