on:
  push:
    branches:
      - major
      - minor
      - patch

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the source code
        uses: actions/checkout@v3

      - name: Set up Dhall
        uses: dhall-lang/setup-dhall@v4
        with:
          version: 1.41.1

      - name: Build
        run: build-scripts/build.bash

      - name: Upload to object storage
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args:
            --acl public-read
            --follow-symlinks
            --delete
            --exclude '.*/*'
            --exclude 'build-scripts/*'
            --exclude 'src/*'
        env:
          AWS_S3_ENDPOINT: ${{ secrets.S3_ENDPOINT }}
          AWS_REGION: ${{ secrets.S3_REGION }}
          AWS_ACCESS_KEY_ID: ${{ secrets.SA_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.SA_ACCESS_KEY_SECRET }}
          AWS_S3_BUCKET: ${{ secrets.S3_BUCKET }}
          SOURCE_DIR: dist

      - name: Bump version and push tag
        id: tag-release
        uses: anothrNick/github-tag-action@1.39.0
        env:
          RELEASE_BRANCHES: major,minor,patch
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: ${{ github.ref_name }}
          WITH_V: true
